### ISSUE TITLE
Разобраться с плагинами QGIS

### ISSUE THREAD

**Issue by nermakovaa** [webebers/city-view-back#15]
1) локально запустить QGIS
2) загрузить данные из OpenStreetMap (взять СПб, к примеру)
3) попробовать написать простенький плагин

Есть документация, по которой все это можно изучить, https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/index.html (пункт 17.1)

**Comment by sevryukov** [comment]
@AnatolyShev эту задачу в полной мере должны решить все четверо из назначенных? Почему не разбиты на три отдельные задачи?

**Comment by AnatolyShev** [comment]
@sevryukov Да, так и есть. Эта задача не разбита на отдельные три подзадачи для удобства навигации (поиска) и из-за того, что они считаются частью одного цельного задания.

**Comment by sevryukov** [comment]
@AnatolyShev что Вы вкладываете в понятие "удобство навигации"? Про чтение статей и ТЗ у вас по 2-3 задачи, когда как тут, где очевидное деление - одна. Какие признаки говорят о том, что задачу надо разделить или задачи надо объединить? Может ли без перехода к очередной задаче быть выполнена предшествующая? Что является условием для выполнения задачи (DoR - см. мой практикум по ведению бэклога) и её результатом (DoD)?
Ответы на эти вопросы помогут в принятии решения о разделении или объединении задач.

P.S. Разделяй и властвуй
