### ISSUE TITLE
Продумать бизнес модель

### ISSUE THREAD

**Issue by AnatolyShev** [webebers/city-view-back#17]
- Придумать как "будем" продавать наш проект, надо сделать до встречи в понедельник с бизнес трекером.

**Comment by GeorgiySurkov** [comment]
https://www.scaleway.com/en/blog/how-to-monetize-your-open-source-project/

**Comment by GeorgiySurkov** [comment]
Нам подходят:
- Платная поддержка опенсорс продукта
- Open Core model – платная версия по закрытой лицензии с большим количеством фич (пример: GitLab)

**Comment by GeorgiySurkov** [comment]
https://github.com/PayDevs/awesome-oss-monetization/tree/main

**Comment by AnatolyShev** [comment]
Документ для заполнения бизнес модели по Остервальдеру:
https://docs.google.com/document/d/1QNxtH54_BDdaDZRjqYEc9rAJpIDgKnfnfIiiqZkdZeQ/edit?usp=sharing

**Comment by AnatolyShev** [comment]
Бизнес модель (по Остервальдеру) додумали и дописали вместе с бизнес трекером 13.11.2023.
