### ISSUE TITLE
Составить ТЗ

### ISSUE THREAD

**Issue by GeorgiySurkov** [webebers/city-view-back#9]
Документ: https://docs.google.com/document/d/1snAvnH-A0FP1Cz45PaOXdyENaN67yit3ljeTxY8rBdI/edit?usp=sharing

**Comment by AnatolyShev** [comment]
Полезная статья для написания ТЗ с ссылками на стандарты:
https://habr.com/ru/articles/328822/

**Comment by GeorgiySurkov** [comment]
## Вопросы:

- Какую проблему должен решать наш сервис?
    - Есть улично дорожная сеть. Можно получить по OSM. Сервис должен позовлять это делать (показывать карту?). В первую очередь доложен брать топологию сети. Это граф, где узлы - это перекрестки, ребра - это дороги соединяющие перекрестки. В OSM узлами являются все преломления дороги. В этом смысле у нас появляется проблема, что граф перегружен большим количеством узлов. (удалять вершины, где входит и выходит по одному ребру? дуга от перекрестка до перекрестка). В OSM въезд во двор тоже является перекрестком (проблема). Проблема большой сети в дорогах внутри дворов. Они тоже должны быть отображены. Нам дадут доступ к поделкам предыдущих команд. Мосалев в курсе этой проблематики, с ним можно об этом поговрить. Чего не было раньше и что точно надо. Помимо автомобилей есть и пешеходы. У пешеходов свои дороги.  Может проходить не только по дороге, но и просто (типа по газону?). Расстояние надо учитывать в дугах графа. Вершина бывает, когда дорога сузилась (3 полосы → 2 полосы). Хочется это в виде слоев: OSM, для машин, для пешеходов.
    - Что такое анализ? Нахождение разных величин для графа (уточнить потом список этих величин). Вывод какого-то рейтинга. Это надо мочь отображать. Можно использовать для этого существующие средства (2гис qgis например, там можно писать плагины).
    - Не надо заморачиваться, что люди ходят по газонам. Исключительно использовать официальные дорожки.
- как загружается карта города в сервис? какие форматы входных данных?
    - Кроме OSM ничего не знает.
- *выявлять самоорганизующиеся городские пространства* и пространства (районы), план (структура) которых задан(-а) регулярным (системным) проектом (self-organization vs top-down planning)?
    - для их выявления надо посчитать, подчиняются ли дуги степенному закону. Надо будет выявлять самоорганизованные и организованные сверху вниз топологии. надо будет представлять улицы целиком как узлы. можно будет представить улицы в таблице, где в одной колонке уникальная улица, во втором столбце количество пересечений с другими улицами. Дальше ранжируем.. (хз не понял дальше, прочитаем подробнее потом). Список всех улиц берем в csv или excel. Число улиц, с которыми она пересекается, ее район, ее муниципальное образование.
    - статью про это он выложит.
- Какую доп информацию нам изучить по теме?
    - Вышлет нам статьи научные.
- вычислять параметры данной топологии. Какие параметры?
    - Какие величины считать:
        - Betweeness кратчайшие маршруты через этот узел
        - Page rank. Сколько узлов ссылается на этот узел.
        - помозговать, что можно еще посчитать
    - на чем писать, qgis, на какие платформы заземлить.
- Какие требования к технологиям?
    - спросить у Сергея Юрьевича, по этому моменту вместе все проговорим. это будет отдельная встреча.
- Есть ли какие-то существующие системы, с которыми нам нужно будет интегрироваться?
    - qgis есть много плагинов. удобен для визуализации.
    - от нас поиск новых технологий
    - спрашивать у Сергея Юрьевича
- Какие есть существующие сервисы, которые решают проблему?
    - для всего пользуемся qgisом, но он сильно ограничивает. Чуть шаг в сторону и приходится что-то изобретать.
- Надо ли будет как-то развертывать эту систему? Какие ограничения по среде, где будет развернута система?

## Договоренности:

Крылатов скидывает статьи.

Крылатов скидывает реализованные проекты прошлых лет.

Мы изучаем инфу, выбираем технологии.

Договариваемся на следующую встречу.

## Протокол встречи

## Требования проекта

Разработать веб-ориентированное приложение для исследования и анализа улично-дорожной сети города, позволяющее выявлять самоорганизующиеся городские пространства и пространства (районы), план (структура) которых задан(-а) регулярным (системным) проектом (self-organization vs top-down planning). Приложение должно позволять загружать и обрабатывать карту любого города (на примере, Санкт-Петербурга), представлять и визуализировать городскую топологию улиц в виде графа, вычислять параметры данной топологии.

## Описание

Сервис должен позволять устанавливать среднее число связей (связь – это пересечение улиц) в топологии города для каждой улицы города со всеми остальными как в городе в целом, так и по отдельным районам.

**Comment by GeorgiySurkov** [comment]
^^^ Мои записи со встреч, полезны для составления ТЗ

**Comment by nermakovaa** [comment]
ссылка на первый вариант ТЗ https://github.com/webebers/docs/blob/master/technic_requirements.ipynb

**Comment by AnatolyShev** [comment]
Необходимо отредактировать первый вариант ТЗ и выслать его Александру Юрьевичу.

**Comment by sevryukov** [comment]
@AnatolyShev @nermakovaa задача закрыта, но ТЗ осталось прежним (хотя на встрече были замечания и согласие с вашей стороны о том, что да, надо править ТЗ).
Где можно ознакомиться с актуальной версией?
